// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GenTokenRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenTokenRequest) Reset()         { *m = GenTokenRequest{} }
func (m *GenTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GenTokenRequest) ProtoMessage()    {}
func (*GenTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *GenTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenTokenRequest.Unmarshal(m, b)
}
func (m *GenTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenTokenRequest.Marshal(b, m, deterministic)
}
func (m *GenTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenTokenRequest.Merge(m, src)
}
func (m *GenTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GenTokenRequest.Size(m)
}
func (m *GenTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenTokenRequest proto.InternalMessageInfo

func (m *GenTokenRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GenTokenRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type GenTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenTokenResponse) Reset()         { *m = GenTokenResponse{} }
func (m *GenTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GenTokenResponse) ProtoMessage()    {}
func (*GenTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *GenTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenTokenResponse.Unmarshal(m, b)
}
func (m *GenTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenTokenResponse.Marshal(b, m, deterministic)
}
func (m *GenTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenTokenResponse.Merge(m, src)
}
func (m *GenTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GenTokenResponse.Size(m)
}
func (m *GenTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenTokenResponse proto.InternalMessageInfo

func (m *GenTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenRequest) Reset()         { *m = CheckTokenRequest{} }
func (m *CheckTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CheckTokenRequest) ProtoMessage()    {}
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *CheckTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenRequest.Unmarshal(m, b)
}
func (m *CheckTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenRequest.Marshal(b, m, deterministic)
}
func (m *CheckTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenRequest.Merge(m, src)
}
func (m *CheckTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CheckTokenRequest.Size(m)
}
func (m *CheckTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenRequest proto.InternalMessageInfo

func (m *CheckTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckTokenResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenResponse) Reset()         { *m = CheckTokenResponse{} }
func (m *CheckTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CheckTokenResponse) ProtoMessage()    {}
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *CheckTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenResponse.Unmarshal(m, b)
}
func (m *CheckTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenResponse.Marshal(b, m, deterministic)
}
func (m *CheckTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenResponse.Merge(m, src)
}
func (m *CheckTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CheckTokenResponse.Size(m)
}
func (m *CheckTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenResponse proto.InternalMessageInfo

func (m *CheckTokenResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*GenTokenRequest)(nil), "auth.GenTokenRequest")
	proto.RegisterType((*GenTokenResponse)(nil), "auth.GenTokenResponse")
	proto.RegisterType((*CheckTokenRequest)(nil), "auth.CheckTokenRequest")
	proto.RegisterType((*CheckTokenResponse)(nil), "auth.CheckTokenResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x4c, 0x6a, 0x3a, 0x82, 0x7f, 0x06, 0xad, 0x4b, 0x0e, 0x52, 0x72, 0x8a, 0x20,
	0x3d, 0xd4, 0x93, 0x27, 0x11, 0x0f, 0xe2, 0x75, 0xd1, 0x0f, 0x10, 0x93, 0xc1, 0x84, 0xda, 0x24,
	0xee, 0x1f, 0xf0, 0xec, 0x27, 0x97, 0x9d, 0x5d, 0xab, 0xb6, 0xde, 0xf6, 0xbd, 0x79, 0xbc, 0xf9,
	0x0d, 0x0b, 0x50, 0x59, 0xd3, 0x2e, 0x46, 0x35, 0x98, 0x01, 0x13, 0xf7, 0x2e, 0x3e, 0x20, 0x79,
	0xd6, 0xa4, 0xf0, 0x10, 0xe2, 0xae, 0x11, 0xd1, 0x3c, 0x2a, 0x53, 0x19, 0x77, 0x0d, 0xe6, 0x90,
	0x59, 0x4d, 0xaa, 0xaf, 0xd6, 0x24, 0xe2, 0x79, 0x54, 0x4e, 0xe5, 0x46, 0xe3, 0x29, 0xa4, 0xb4,
	0xae, 0xba, 0x37, 0xb1, 0xc7, 0x03, 0x2f, 0x50, 0xc0, 0x7e, 0xd5, 0x34, 0x8a, 0xb4, 0x16, 0x09,
	0xfb, 0xdf, 0xd2, 0xe5, 0xc7, 0x76, 0xe8, 0x49, 0xa4, 0x3e, 0xcf, 0xa2, 0x78, 0x84, 0xa3, 0x07,
	0xea, 0x9f, 0x86, 0x15, 0xf5, 0x92, 0xde, 0x2d, 0x69, 0x83, 0x17, 0x90, 0xb8, 0x25, 0x8c, 0x71,
	0xb0, 0x84, 0x05, 0xd3, 0x3a, 0x3c, 0xc9, 0x3e, 0xce, 0x60, 0xa2, 0xa9, 0x56, 0x64, 0x02, 0x52,
	0x50, 0x45, 0x09, 0xc7, 0x3f, 0x55, 0x7a, 0x1c, 0x7a, 0xcd, 0x90, 0xc6, 0x19, 0x5c, 0x36, 0x95,
	0x5e, 0x14, 0x97, 0x70, 0x72, 0xdf, 0x52, 0xbd, 0xfa, 0xb3, 0xf6, 0xff, 0xe8, 0x15, 0xe0, 0xef,
	0x68, 0xa8, 0x75, 0x08, 0xa6, 0x32, 0x56, 0x73, 0x38, 0x93, 0x41, 0x2d, 0x3f, 0x23, 0x48, 0xee,
	0xac, 0x69, 0xf1, 0x06, 0xb2, 0xd7, 0xc0, 0x82, 0x67, 0xfe, 0x82, 0xad, 0x33, 0xf3, 0xd9, 0xb6,
	0x1d, 0xba, 0x6f, 0x01, 0xea, 0xcd, 0x46, 0x3c, 0xf7, 0xa9, 0x1d, 0xdc, 0x5c, 0xec, 0x0e, 0x7c,
	0xc1, 0xcb, 0x84, 0x7f, 0xf6, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xf6, 0x1d, 0x59, 0xe7,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	GenToken(ctx context.Context, in *GenTokenRequest, opts ...grpc.CallOption) (*GenTokenResponse, error)
	CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) GenToken(ctx context.Context, in *GenTokenRequest, opts ...grpc.CallOption) (*GenTokenResponse, error) {
	out := new(GenTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/genToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error) {
	out := new(CheckTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/checkToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	GenToken(context.Context, *GenTokenRequest) (*GenTokenResponse, error)
	CheckToken(context.Context, *CheckTokenRequest) (*CheckTokenResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) GenToken(ctx context.Context, req *GenTokenRequest) (*GenTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenToken not implemented")
}
func (*UnimplementedAuthServer) CheckToken(ctx context.Context, req *CheckTokenRequest) (*CheckTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckToken not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_GenToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GenToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/GenToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GenToken(ctx, req.(*GenTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CheckToken(ctx, req.(*CheckTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "genToken",
			Handler:    _Auth_GenToken_Handler,
		},
		{
			MethodName: "checkToken",
			Handler:    _Auth_CheckToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
