// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package posts

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	pb "micr-go/services/users/pb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	// pmongo.ObjectId id = 1 [(tagger.tags) = "bson:\"_id,omitempty\"" ];
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Slug                 string               `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	UserId               string               `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Post) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Post) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Post) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Post) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreatePostRequest struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type CreatePostResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreatePostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListPostRequest struct {
	Page                 string   `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              string   `protobuf:"bytes,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostRequest) Reset()         { *m = ListPostRequest{} }
func (m *ListPostRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostRequest) ProtoMessage()    {}
func (*ListPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *ListPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostRequest.Unmarshal(m, b)
}
func (m *ListPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostRequest.Marshal(b, m, deterministic)
}
func (m *ListPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostRequest.Merge(m, src)
}
func (m *ListPostRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostRequest.Size(m)
}
func (m *ListPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostRequest proto.InternalMessageInfo

func (m *ListPostRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *ListPostRequest) GetPerPage() string {
	if m != nil {
		return m.PerPage
	}
	return ""
}

type PostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	User                 *pb.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{4}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *PostResponse) GetUser() *pb.User {
	if m != nil {
		return m.User
	}
	return nil
}

type ListPostResponse struct {
	Status               bool            `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*PostResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListPostResponse) Reset()         { *m = ListPostResponse{} }
func (m *ListPostResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostResponse) ProtoMessage()    {}
func (*ListPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{5}
}

func (m *ListPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostResponse.Unmarshal(m, b)
}
func (m *ListPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostResponse.Marshal(b, m, deterministic)
}
func (m *ListPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostResponse.Merge(m, src)
}
func (m *ListPostResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostResponse.Size(m)
}
func (m *ListPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostResponse proto.InternalMessageInfo

func (m *ListPostResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ListPostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListPostResponse) GetData() []*PostResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "posts.Post")
	proto.RegisterType((*CreatePostRequest)(nil), "posts.CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "posts.CreatePostResponse")
	proto.RegisterType((*ListPostRequest)(nil), "posts.ListPostRequest")
	proto.RegisterType((*PostResponse)(nil), "posts.PostResponse")
	proto.RegisterType((*ListPostResponse)(nil), "posts.ListPostResponse")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1) }

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x25, 0x33, 0x99, 0x8f, 0xad, 0x88, 0x1f, 0xa5, 0xec, 0xf6, 0xe6, 0xb2, 0x43, 0x10, 0x9c,
	0x8b, 0x09, 0x8c, 0x1e, 0x04, 0x2f, 0x2e, 0x82, 0x20, 0x78, 0x18, 0x82, 0x9e, 0x97, 0x4c, 0xba,
	0x0d, 0x0d, 0x93, 0xed, 0xb6, 0xab, 0xe3, 0x5f, 0xf0, 0xe7, 0xfa, 0x17, 0xa4, 0x2b, 0x89, 0x13,
	0x5d, 0x61, 0xc1, 0x5b, 0x7d, 0xbc, 0x57, 0x79, 0xef, 0xa5, 0x01, 0xac, 0x21, 0x9f, 0x5b, 0x67,
	0xbc, 0xc1, 0x45, 0xa8, 0x29, 0xbd, 0x6a, 0x8c, 0x69, 0x8e, 0xaa, 0xe0, 0xe1, 0xa1, 0xfb, 0x5a,
	0x78, 0xdd, 0x2a, 0xf2, 0x55, 0x6b, 0x7b, 0x5c, 0xfa, 0xbc, 0xd5, 0xb5, 0x7b, 0xd9, 0x98, 0x82,
	0x94, 0xfb, 0xae, 0x6b, 0x45, 0x45, 0x47, 0xca, 0x51, 0x61, 0x0f, 0x5c, 0xf4, 0xa8, 0xec, 0x67,
	0x04, 0xf1, 0xde, 0x90, 0xc7, 0x87, 0x30, 0xd3, 0x52, 0x44, 0x9b, 0x68, 0x7b, 0x56, 0xce, 0xb4,
	0xc4, 0x67, 0xb0, 0xf0, 0xda, 0x1f, 0x95, 0x98, 0xf1, 0xa8, 0x6f, 0x70, 0x03, 0x89, 0x54, 0x54,
	0x3b, 0x6d, 0xbd, 0x36, 0xb7, 0x62, 0xce, 0xbb, 0xe9, 0x08, 0x11, 0x62, 0x3a, 0x76, 0x8d, 0x88,
	0x79, 0xc5, 0x35, 0x5e, 0xc0, 0x2a, 0x7c, 0xf2, 0x46, 0x4b, 0xb1, 0xe0, 0xf1, 0x32, 0xb4, 0x1f,
	0x25, 0xbe, 0x81, 0xb3, 0xda, 0xa9, 0xca, 0x2b, 0x79, 0xed, 0xc5, 0x72, 0x13, 0x6d, 0x93, 0x5d,
	0x9a, 0xf7, 0xc6, 0xf2, 0xd1, 0x58, 0xfe, 0x79, 0x34, 0x56, 0x9e, 0xc0, 0x81, 0xd9, 0x59, 0x39,
	0x30, 0x57, 0xf7, 0x33, 0x7f, 0x83, 0xb3, 0xd7, 0xf0, 0xe4, 0x3d, 0x9f, 0x09, 0xb6, 0x4b, 0xf5,
	0xad, 0x53, 0xe4, 0xf1, 0x0a, 0xe2, 0x10, 0x2b, 0xfb, 0x4f, 0x76, 0x49, 0xce, 0x19, 0xe7, 0x8c,
	0xe0, 0x45, 0xf6, 0x01, 0x70, 0xca, 0x22, 0x6b, 0x6e, 0x49, 0xe1, 0x39, 0x2c, 0xc9, 0x57, 0xbe,
	0x23, 0x26, 0xae, 0xcb, 0xa1, 0x43, 0x01, 0xab, 0x56, 0x11, 0x55, 0xcd, 0x18, 0xdf, 0xd8, 0x66,
	0xef, 0xe0, 0xd1, 0x27, 0x4d, 0x7e, 0xfa, 0x6d, 0x84, 0xd8, 0x06, 0x64, 0x9f, 0x3d, 0xd7, 0x78,
	0x09, 0x6b, 0xab, 0xdc, 0x8d, 0x9d, 0x5c, 0xb0, 0xca, 0xed, 0xc3, 0x85, 0x3d, 0x3c, 0xf8, 0x43,
	0xc3, 0x7d, 0xd2, 0x03, 0x20, 0xc4, 0xcd, 0x77, 0x02, 0x80, 0x9f, 0x41, 0xfe, 0x85, 0x94, 0x2b,
	0x79, 0x91, 0xb5, 0xf0, 0xf8, 0xa4, 0xe9, 0x7f, 0x9d, 0xe1, 0x0b, 0x88, 0x65, 0xe5, 0x2b, 0x31,
	0xdf, 0xcc, 0xb7, 0xc9, 0xee, 0xe9, 0x54, 0xc7, 0x70, 0xb4, 0x64, 0xc0, 0xee, 0x47, 0x04, 0x8b,
	0x30, 0x26, 0xbc, 0x06, 0x38, 0x85, 0x8a, 0x62, 0xa0, 0xdc, 0xf9, 0x3b, 0xe9, 0xe5, 0x3f, 0x36,
	0x83, 0xce, 0xb7, 0xb0, 0x1e, 0xb5, 0xe3, 0xf9, 0x00, 0xfb, 0x2b, 0xe0, 0xf4, 0xe2, 0xce, 0xbc,
	0x27, 0x1f, 0x96, 0xfc, 0x52, 0x5e, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xf1, 0x24, 0x42,
	0x5f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostsClient is the client API for Posts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	ListPost(ctx context.Context, in *ListPostRequest, opts ...grpc.CallOption) (*ListPostResponse, error)
}

type postsClient struct {
	cc *grpc.ClientConn
}

func NewPostsClient(cc *grpc.ClientConn) PostsClient {
	return &postsClient{cc}
}

func (c *postsClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/posts.Posts/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsClient) ListPost(ctx context.Context, in *ListPostRequest, opts ...grpc.CallOption) (*ListPostResponse, error) {
	out := new(ListPostResponse)
	err := c.cc.Invoke(ctx, "/posts.Posts/ListPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServer is the server API for Posts service.
type PostsServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	ListPost(context.Context, *ListPostRequest) (*ListPostResponse, error)
}

// UnimplementedPostsServer can be embedded to have forward compatible implementations.
type UnimplementedPostsServer struct {
}

func (*UnimplementedPostsServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostsServer) ListPost(ctx context.Context, req *ListPostRequest) (*ListPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPost not implemented")
}

func RegisterPostsServer(s *grpc.Server, srv PostsServer) {
	s.RegisterService(&_Posts_serviceDesc, srv)
}

func _Posts_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/posts.Posts/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Posts_ListPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServer).ListPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/posts.Posts/ListPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServer).ListPost(ctx, req.(*ListPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Posts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "posts.Posts",
	HandlerType: (*PostsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _Posts_CreatePost_Handler,
		},
		{
			MethodName: "ListPost",
			Handler:    _Posts_ListPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
